-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

-- Notes (matches the starter HTML / Account page)
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  created_at timestamptz default now()
);

alter table public.notes enable row level security;

create policy "Users read own notes"
  on public.notes for select
  using (auth.uid() = user_id);

create policy "Users insert own notes"
  on public.notes for insert
  with check (auth.uid() = user_id);

create policy "Users delete own notes"
  on public.notes for delete
  using (auth.uid() = user_id);

-- Lobby campaign cloud sync (Capture Deck)
create table if not exists public.user_data (
  user_id uuid primary key references auth.users,
  lobby_campaign jsonb,
  updated_at timestamptz default now()
);

alter table public.user_data enable row level security;

create policy "Users manage own data"
  on public.user_data for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
